### ISSUE TITLE
We're only seeking minimalist solutions

### ISSUE THREAD

**Issue by faddat** [ausbitbank/ausbitbank.github.io#1]
And HOT DAMN!

You got yourself one here.  Do you mind hopping over to the dawn chat at https://chat.anisotropic.systems/

and tell us all about it and help us design dx that sufficently meets your incredible standards for minimalism.

**Comment by ausbitbank** [comment]
I'm back up now, will be lurking in Dawn and try to tidy this code up a bit more today. It's still missing a few important features but I'm happy to help

**Comment by faddat** [comment]
It is truly fantastic work.
